<a href="https://colab.research.google.com/github/pathces-gone/study-python-stock/blob/main/price_naver_finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# https://seong6496.tistory.com/156
import requests
import pandas as pd
from IPython.display import HTML

class Stock:
  def __init__(self, code):
    self.code = code

  def get_dataframe(self):
    URL = f"https://finance.naver.com/item/main.nhn?code={self.code}"
    r = requests.get(URL)
    df = pd.read_html(r.text)[3]
    return df
  
  def set_index(self):
    df = self.get_dataframe()
    df.set_index(df.columns[0], inplace=True)
    df.index.rename('주요재무정보', inplace=True)
    df.columns = df.columns.droplevel(2)

    self.annual_data = pd.DataFrame(df).xs('최근 연간 실적', axis=1)
    self.quater_data = pd.DataFrame(df).xs('최근 분기 실적', axis=1)
    self.df = df

  def display(self, cmd):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 1000)
    pd.set_option('display.colheader_justify', 'center')
    pd.set_option('display.precision', 3)
    
    if cmd == 0:
      display(self.df)
    elif cmd == 1:
      display(self.annual_data)
    elif cmd == 2:
      display(self.quater_data)
    else:
      print()
s = Stock(code = '005930')
s.set_index()
s.display(1)

            2018.12    2019.12    2020.12   2021.12(E)
주요재무정보
매출액        2.438e+06  2.304e+06  2.368e+06   2.778e+06
영업이익       5.889e+05  2.777e+05  3.599e+05   5.283e+05
당기순이익      4.434e+05  2.174e+05  2.641e+05   4.032e+05
영업이익률      2.416e+01  1.205e+01  1.520e+01   1.902e+01
순이익률       1.819e+01  9.440e+00  1.115e+01   1.451e+01
ROE(지배주주)  1.963e+01  8.690e+00  9.980e+00   1.416e+01
부채비율       3.697e+01  3.412e+01  3.707e+01         NaN
당좌비율       2.041e+02  2.336e+02  2.148e+02         NaN
유보율        2.753e+04  2.886e+04  3.069e+04         NaN
EPS(원)     6.024e+03  3.166e+03  3.841e+03   5.848e+03
PER(배)     6.420e+00  1.763e+01  2.109e+01   1.334e+01
BPS(원)     3.534e+04  3.753e+04  3.941e+04   4.320e+04
PBR(배)     1.090e+00  1.490e+00  2.060e+00   1.810e+00
주당배당금(원)   1.416e+03  1.416e+03  2.994e+03   1.681e+03
시가배당률(%)   3.660e+00  2.540e+00  3.700e+00         NaN
배당성향(%)    2.192e+01  4.473e+01  7.795e+01         NaN